// packages/frontend-react/src/views/top-menu/components/right-btns/index.tsx

import Search from './components/Search';
import Time from './components/Time';
import IconBell from '@/assets/imgs/icon-bell.png';
import IconHelp from '@/assets/imgs/icon-help-circle.png';
import AvatarWomanShort from '@/assets/imgs/avatar-woman-short.png';

export default function RightBtns() {
  return (
    <div className="flex items-center">
      <Search />
      <Time />
      <img className="w-24px h-24px mr-22px" src={IconBell} alt="" />
      <img className="w-24px h-24px mr-20px"  src={IconHelp} alt="" />
      <img className="w-36px h-36px"  src={AvatarWomanShort} alt="" />
    </div>
  )
}

// packages/frontend-vue/src/views/top-menu/components/right-btns/index.vue
<template>
  <div class="flex items-center">
    <Search />
    <Time />
    <img class="w-24px h-24px mr-22px" :src="IconBell" alt="">
    <img class="w-24px h-24px mr-20px"  :src="IconHelp" alt="">
    <img class="w-36px h-36px"  :src="AvatarWomanShort" alt="">
  </div>
</template>

<script setup lang="ts">
import Search from './components/Search.vue';
import Time from './components/Time.vue';
import IconBell from '@/assets/imgs/icon-bell.png';
import IconHelp from '@/assets/imgs/icon-help-circle.png';
import AvatarWomanShort from '@/assets/imgs/avatar-woman-short.png';
</script>
