// packages/_backup/frontend-vue/src/views/channel/channel-list/index.vue
<template>
  <div class="flex flex-shrink-0 flex-col h-100% w-340px bg-channel-list overflow-scroll"> 
    <Search />
    <template v-for="(item, index) in channels" :key="index">
      <Item :data="item" :is-active="index === activeIndex" />
    </template>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue';
import Item from './components/Item.vue';
import Search from './components/Search.vue';

const activeIndex = ref(1);

const channels = reactive([{
  title: 'Courtney Henry',
  avatar: '',
  message: 'So, what\'s your plan this weekend?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}, {
  title: 'Albert Flores',
  avatar: '',
  message: 'What\'s the progress on that task?',
}])

</script>

// packages/frontend/src/views/channel/channel-list/index.tsx
import { useState, useSyncExternalStore } from 'react';
import { getSearchParams } from '@/utils/url';
import Item from './components/Item';
import Search from './components/Search';
import { useChannels } from '@/hooks/channel.hook';

export default function ChannelList() {
  const [activeIndex, setActiveIndex] = useState(1);
  const [channels] = useChannels();

  function handleClick(index: number) {
    setActiveIndex(index);
  }

  return (
    <div className="flex flex-shrink-0 flex-col h-100% w-340px bg-channel-list overflow-scroll">
      <Search />
      {channels.map((item, index) => (
        <div key={index} onClick={() => handleClick(index)}>
          <Item data={item} isActive={index === activeIndex} />
        </div>
      ))}
    </div>
  );
}
